apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  description: The admin business unit
spec:
  type: business-unit
  profile:
    displayName: Admin
    email: admin@example.com
  children: [backstage, other]
  members: [user-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user-a
spec:
  profile:
    displayName: user-a
    email: user-a@example.com
  memberOf: [admin]
