apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user-a
spec:
  profile:
    displayName: user-a
    email: user-a@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [admin]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  description: The admin business unit
spec:
  type: business-unit
  profile:
    displayName: Admin
    email: admin@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [user-a]